[mypy]
python_version = 3.11

# Treat paths as packages starting at the repo root.
explicit_package_bases = True
mypy_path = .

# Be lenient with 3rd-party/experimental modules for now.
ignore_missing_imports = True
